CREATE TABLE "GCG_5447_Cost_Price"(
 "TRMNL" CHAR(3) DEFAULT '   ',
 "UserID" CHAR(8) DEFAULT '   ',
 "Part" CHAR(20) NOT NULL,
 "Description" CHAR(30),
 "Customer" CHAR(6) NOT NULL,
 "Name" CHAR(30),
 "Old_List_Price" NUMERIC(13,5) DEFAULT '0',
 "Old_Alt_Price" NUMERIC(15,6) DEFAULT '0',
 "New_List_Price" NUMERIC(13,5) DEFAULT '0',
 "New_Alt_Price" NUMERIC(15,6) DEFAULT '0',
 "Cost" NUMERIC(16,6) DEFAULT '0',
 "Material" NUMERIC(14,6) DEFAULT '0',
 "Labor" NUMERIC(14,6) DEFAULT '0',
 "Outside" NUMERIC(14,6) DEFAULT '0',
 "Overhead" NUMERIC(14,6) DEFAULT '0',
 "Freight" NUMERIC(14,6) DEFAULT '0',
 "Other" NUMERIC(14,6) DEFAULT '0',
 "Est_Labor1" NUMERIC(5,2) DEFAULT '0',
 "Est_Labor_2" NUMERIC(5,2) DEFAULT '0',
 "Est_Labor_3" NUMERIC(5,2) DEFAULT '0',
 "Est_Labor_4" NUMERIC(5,2) DEFAULT '0',
 "Est_Labor_5" NUMERIC(5,2) DEFAULT '0',
 "Est_Labor_6" NUMERIC(5,2) DEFAULT '0',
 "Est_Material_1" NUMERIC(5,2) DEFAULT '0',
 "Est_Material_2" NUMERIC(5,2) DEFAULT '0',
 "Est_Material_3" NUMERIC(5,2) DEFAULT '0',
 "Est_Material_4" NUMERIC(5,2) DEFAULT '0',
 "Est_Material_5" NUMERIC(5,2) DEFAULT '0',
 "Est_Material_6" NUMERIC(5,2) DEFAULT '0',
 "Est_Outside_1" NUMERIC(5,2) DEFAULT '0',
 "Est_Outside_2" NUMERIC(5,2) DEFAULT '0',
 "Est_Outside_3" NUMERIC(5,2) DEFAULT '0',
 "Est_Outside_4" NUMERIC(5,2) DEFAULT '0',
 "Est_Outside_5" NUMERIC(5,2) DEFAULT '0',
 "Est_Outside_6" NUMERIC(5,2) DEFAULT '0',
 "Price_1" NUMERIC(15,6) DEFAULT '0',
 "Price_2" NUMERIC(15,6) DEFAULT '0',
 "Price_3" NUMERIC(15,6) DEFAULT '0',
 "Price_4" NUMERIC(15,6) DEFAULT '0',
 "IsBom" CHAR(1) DEFAULT 'N' NOT NULL,
 "GenDate" INTEGER DEFAULT '0' NOT NULL,
 "PriceSelected" SMALLINT DEFAULT '1',
 "GenTime" INTEGER DEFAULT '1',
 "QuoteNumber" CHAR(7) );
CREATE INDEX "GCG_5447_Customer2" USING 3 IN DICTIONARY  ON "GCG_5447_Cost_Price" ( "Customer" );
CREATE INDEX "GCG_5447_GenDate2" USING 4 IN DICTIONARY  ON "GCG_5447_Cost_Price" ( "GenDate" );
CREATE INDEX "GCG_5447_GenTime2" USING 5 IN DICTIONARY  ON "GCG_5447_Cost_Price" ( "GenTime" );
CREATE INDEX "GCG_5447_Quote2" USING 6 IN DICTIONARY  ON "GCG_5447_Cost_Price" ( "QuoteNumber" );
CREATE INDEX "GCG_5447_TRMNL2" USING 1 IN DICTIONARY  ON "GCG_5447_Cost_Price" ( "TRMNL" );
CREATE INDEX "GCG_5447_UserID2" USING 0 IN DICTIONARY  ON "GCG_5447_Cost_Price" ( "UserID" );
